server:
  port: 8081

spring:
  #Liquibase
  liquibase:
    change-log: ${LIQUIBASE_CHANGE_LOG:classpath:db-changelog/changelog-dev.xml}

  #JPA
  datasource:
    url: jdbc:postgresql://localhost:5432/everest-db
    #url: jdbc:postgresql://localhost:5432/artist-db
    username: postgres
    password:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        ddl-auto: none