server:
  port: 8082

spring:
  #Liquibase
  liquibase:
    change-log: ${LIQUIBASE_CHANGE_LOG:classpath:db-changelog/changelog-dev.xml}

  h2:
    console:
      enable: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true

  #JPA
  datasource:
    url: jdbc:h2:mem:spyglass;DB_CLOSE_DELAY=-1
    username: admin
    password:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        ddl-auto: none